// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWRvIlGdBR2WuyuK120CT49yXU3Tqtzzk',
    appId: '1:801322884372:android:8e110f322864d5add2b601',
    messagingSenderId: '801322884372',
    projectId: 'shoppingcart-2df55',
    storageBucket: 'shoppingcart-2df55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZAAcN0ehnKgqrqC5Gt8mTaIf59xwQrBo',
    appId: '1:801322884372:ios:69301033946fc2a0d2b601',
    messagingSenderId: '801322884372',
    projectId: 'shoppingcart-2df55',
    storageBucket: 'shoppingcart-2df55.appspot.com',
    androidClientId: '801322884372-ihf1oijkaemggvhehrmdqb1kjd5lqea1.apps.googleusercontent.com',
    iosClientId: '801322884372-ju11cfvrpcklmuns25691o2s4004d12n.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );
}
